export const metadata = {
  title: {
    
    default: "Next.js Tutorial - CodeDezk",
    template: "%s | CodeDezk"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{background: "lightblue", padding: "1rem"}}>Header</header>
        {children}
        <footer style={{ background: "ghostwhite", padding: "1rem" }}>Footer</footer>
      </body>
    </html>
  )
}
